apiVersion: v1
kind: Service
metadata:
  name: svc-sessionaffinity
spec:
  type: ClusterIP
  selector:
    app: nginx
  sessionAffinity: ClientIP  
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
