apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  selector:
    app: nginx
  type: ClusterIP  
  clusterIP: None  # 设置成None，就表示是无头服务
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
