# 默认运行一个nginx
apiVersion: v1
kind: Pod
metadata:
  name: pod-run
spec:
  containers:
  - name: nginx-run
    image: harbor.kubemsb.com/library/nginx:latest
    ports:
    - name: http
      containerPort: 80
