kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysqldb-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  storagepolicyname: "zwq-Space-Efficient"
  fstype: ext4

