# 演示标签使用
apiVersion: v1
kind: Pod
metadata:
  name: pod-label
  labels:
    app: pod-labels
spec:
  containers:
  - name: c
    image: harbor.kubemsb.com/library/nginx-web:0.1
    ports:
    - containerPort: 80
