apiVersion: v1
kind: Pod
metadata:
  name: generic-secret-pod
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    volumeMounts:
    - name: generic-secret-cmd
      mountPath: /secret-1/
    - name: generic-secret-yaml
      mountPath: /secret-2/
  volumes:
  - name: generic-secret-cmd
    secret:
      secretName: generic-secret-cmd
      defaultMode: 0660
  - name: generic-secret-yaml
    secret:
      secretName: generic-secret-yaml
      defaultMode: 0660
