apiVersion: v1
kind: Pod
metadata:
  name: secret-tls-nginx-pod
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
    - name: nginx-certs
      mountPath: /etc/nginx/certs
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-https-cm
  - name: nginx-certs
    secret:
      secretName: https-cert
