apiVersion: v1
kind: Pod
metadata:
  name: secret-docker-registry-pod
spec:
  imagePullSecrets:
  - name: private-registry-secret
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/private-registry/nginx-web:0.1
    imagePullPolicy: Always
