apiVersion: v1
kind: Pod
metadata:
  name: nginx-clusterip-pod
  labels:
    app: nginx-clusterip
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-svc
spec:
  type: ClusterIP
  selector:
    app: nginx-clusterip
  ports:
  - name: http
    port: 80
    targetPort: 80
