apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport-pod
  labels:
    app: nginx-nodeport
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-svc
spec:
  type: NodePort
  selector:
    app: nginx-nodeport
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
