apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-local-deploy
  labels:
    app: nginx-local
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-local
  template:
    metadata:
      labels: 
        app: nginx-local
    spec:
      containers:
      - name: nginx-web
        image: harbor.kubemsb.com/library/nginx-web:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-local-svc
spec:
  type: NodePort
  selector:
    app: nginx-local
  externalTrafficPolicy: Local  
  ports:
  - name: http
    port: 8080
    targetPort: 80
    nodePort: 30180
