apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  labels:
    env: cluster-test
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: http
        image: harbor.kubemsb.com/library/nginx-proxy:0.1
        ports:
        - name: nginx-proxy
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  labels:
    env: cluster-test
    app: nginx-proxy
spec:
  type: NodePort
  selector:
    app: nginx-proxy
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
    nodePort: 30180

