apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-web
  labels:
    env: cluster-test
    app: tomcat-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-web
  template:
    metadata:
      labels:
        app: tomcat-web
    spec:
      containers:
      - name: http
        image: harbor.kubemsb.com/library/tomcat-web:0.1
        ports:
        - name: tomcat-web
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-web
  labels:
    env: cluster-test
    app: tomcat-web
spec:
  type: NodePort
  selector:
    app: tomcat-web
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
    nodePort: 30380