apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web
  labels:
    env: cluster-test
    app: django-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-web
  template:
    metadata:
      labels:
        app: django-web
    spec:
      containers:
      - name: http
        image: harbor.kubemsb.com/library/django-web:0.1
        ports:
        - name: django-web
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-web
  labels:
    env: cluster-test
    app: django-web
spec:
  type: NodePort
  selector:
    app: django-web
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: 8000
    nodePort: 30480
