apiVersion: v1
kind: Namespace
metadata:
  name: kubemsb2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-web02
  name: nginx-web02
  namespace: kubemsb2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-web02
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-web02
    spec:
      containers:
      - image: harbor.kubemsb.com/library/nginx-web:0.1
        name: nginx-web
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-web02
  name: nginx-web02
  namespace: kubemsb2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-web02