apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: rate-limit-policy
spec:
  rateLimit:
    rate: 10r/s
    burst: 50
    noDelay: true
    key: ${binary_remote_addr}
    zoneSize: 5M
    rejectCode: 444
