apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: ingress-vs
spec:
  host: www.k8slocal.com
  #policies:
  #- name: rate-limit-policy
  upstreams:
  - name: nginx
    service: nginx-web-svc
    port: 80
  routes:
  - path: /
    action:
      pass: nginx
