apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubemsb-role
  namespace: default
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - pods
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - delete

