apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubemsb-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubemsb-clusterrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubemsb-clusterrole
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubemsb