apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubemsb-clusterrole-mixed
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubemsb-clusterrolebinding-mixed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubemsb-clusterrole-mixed
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubemsb