apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nfs-pvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-nfs-pvc
  template:
    metadata:
      labels:
        app: nginx-nfs-pvc
    spec:    
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: webroot
          mountPath: /usr/share/nginx/html
      volumes:
      - name: webroot
        persistentVolumeClaim: 
          claimName: pvc-nfs
