apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  accessModes: # https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /data/nfs  # nfs共享的目录
    server: 192.168.49.4 # nfs服务目录
