apiVersion: v1
kind: Pod
metadata:
  name: volume-nfs
  labels:
    app: nginx-nfs
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    volumeMounts:
    - name: webroot
      mountPath: /usr/share/nginx/html
  volumes:
  - name: webroot
    nfs:
      path: /data/nfs
      server: 192.168.49.4
