apiVersion: v1
kind: Pod
metadata:
  name: volume-hostpath
spec:
  nodeName: minikube
  containers:
  - name: hp
    image: centos:7
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c", "echo 'hhhhhh' > /data/1.txt"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /data
