apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubemsb-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubemsb-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: kubemsb
