# 初始化容器应用实践

apiVersion: v1
kind: Pod
metadata:
  name: pod-init-test
spec:
  containers:
  - name: busybox
    image: harbor.kubemsb.com/library/busybox:1.28
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "echo app is running! && sleep 3600"]
  initContainers:
  - name: wait-server-starting
    image: harbor.kubemsb.com/library/busybox:1.28
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;do echo wating for myserver;sleep 2;done"]
