# 资源限制limitrange
apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limitrange
spec:
  limits:
  - max:
      cpu: 100m
      memory: 100Mi
    min: 
      cpu: 5m
      memory: 5Mi
    default:
      cpu: 90m
      memory: 90Mi
    defaultRequest:
      cpu: 50m
      memory: 50Mi
    type: Container
