# 默认运行一个nginx
apiVersion: v1
kind: Pod
metadata:
  name: pod-run
spec:
  containers:
  - name: nginx-run
    image: harbor.kubemsb.com/library/nginx:latest
    ports:
    - name: http
      containerPort: 80d
    resources:
      limits:
        memory: 100Mi
        cpu: 101m # CPU超限制了
      requests:
        memory: 50Mi
        cpu: 50m  
