apiVersion: v1
kind: Pod
metadata:
  name: pod-post-start
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
    lifecycle:
      postStart:
        exec:
          command:
          - mkdir
          - -p
          - /usr/share/nginx/haha
