apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-network
spec:
  containers:
  - name: c1
    image: nginx
    imagePullPolicy: IfNotPresent
  - name: c2
    image: nginx
    imagePullPolicy: IfNotPresent
