apiVersion: v1
kind: Namespace
metadata:
  name: pod-study-ns

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-stress-res-overload
  namespace: pod-study-ns
spec:
  containers:
  - name: c1
    image: polinux/stress
    command: ["stress"] # 自定义启动命令
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"  
