apiVersion: v1
kind: Pod
metadata:
  name: pod-stress
spec:
  containers:
  - name: c1
    image: polinux/stress
    command: ["stress"] # 自定义启动命令
    args: ["--vm", "1", "--vm-bytes", "150", "--vm-hang", "1"]

