# 演示nfs类型的存储使用方式
# nfs类型的需要提前搭建好nfs服务器
# 同时nfs服务器存在单点问题，慎重选择。
apiVersion: v1
kind: Pod
metadata:
  name: pod-nfs
spec:
  containers:
  - name: c1
    image: harbor.kubemsb.com/library/nginx-web:0.1
    volumeMounts:
    - name: index-page
      mountPath: /usr/share/nginx/html
  volumes:
  - name: index-page
    nfs:
      path: /data/nfs-data
      server: 192.168.159.21
        