apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  kubemsb-status.cfg: |
    location /nginx-status {
        stub_status on;
    }
  default.conf: |
    server{
        listen 80;
        server_name www.kubemsb.com;
        include /etc/nginx/conf.d/kubemsb-*.cfg;
        location / {
            root /usr/share/nginx/html;
        }
    }
