apiVersion: constraints.gatekeeper.sh/v1beta1
kind: serviceaccount-name-must-equal-namespace
metadata:
  name: sa-must-equal-namespace-constraint
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["ServiceAccount"]
