apiVersion: constraints.gatekeeper.sh/v1beta1
kind: image-pull-must-from-private-registry
metadata:
  name: image-check-constraint
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
  parameters:
    prefix: harbor.kubemsb.com
