apiVersion: v1
kind: Pod
metadata:
  name: nginx-web-pod-nosa
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    imagePullPolicy: IfNotPresent
  automountServiceAccountToken: false
