apiVersion: v1
kind: ServiceAccount
metadata:
  name: with-secret-sa
---
apiVersion: v1
kind: Secret
metadata:
  name:  with-secret-sa-secret
  annotations:
    kubernetes.io/service-account.name: with-secret-sa
type: kubernetes.io/service-account-token
