apiVersion: v1
kind: Pod
metadata:
  name: sa-with-secret-pod
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: service-account-tokens
      mountPath: /var/run/tokens
  serviceAccountName: with-secret-sa    
  volumes:
  - name: service-account-tokens
    projected:
      sources:
      - serviceAccountToken:
          audience: with-secret-sa
          expirationSeconds: 600 
          path: serviceAccountToken
