# kubemsb用户组授予get,watch,list权限
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-viewer
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-viewer-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deploy-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kubemsb
