apiVersion: v1
kind: Namespace
metadata:
  name: kubemsb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zhangsan
  namespace: kubemsb
---
apiVersion: v1
kind: Secret
metadata:
  name: zhangsan-secret
  namespace: kubemsb
  annotations:
    kubernetes.io/service-account.name: zhangsan
type: kubernetes.io/service-account-token
