apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low
value: 100000
description: "低优先级"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high
value: 1000000
description: "搞优先级"
