apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota-priorityclass-high
spec:
  hard:
    requests.cpu: 2
    requests.memory: 1Gi
  scopeSelector:
    matchExpressions:
    - scopeName: PriorityClass
      operator: In
      values: ["high"]
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota-priorityclass-low
spec:
  hard:
    requests.cpu: 1
    requests.memory: 500Mi
  scopeSelector:
    matchExpressions:
    - scopeName: PriorityClass
      operator: In
      values: ["low"]
