# 演示在资源满足情况下，可以顺利创建
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-web-high
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  priorityClassName: high
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-web-low
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  priorityClassName: low 
