# 演示在资源不满足的情况下，资源创建失败
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-web-high-bad
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    resources:
      requests:
        cpu: 2100m
        memory: 100Mi
  priorityClassName: high
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-web-low-bad
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    resources:
      requests:
        cpu: 1100m
        memory: 100Mi
  priorityClassName: low
