apiVersion: v1
kind: Pod
metadata:
  name: resourcequota-ns-calc-resources-pod-0
  namespace: calc-resouces
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: resourcequota-ns-calc-resources-pod-1
  namespace: calc-resouces
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    resources:
      requests:
        cpu: 101m
        memory: 100Mi
