apiVersion: v1
kind: LimitRange
metadata:
  name: calc-resources-lr
spec:
  limits:
  - default:
      cpu: 300m
      memory: 300Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 500m
      memory: 500Mi
    min:
      cpu: 100m
      memory: 100Mi
    type: Container
