apiVersion: v1
kind: Pod
metadata:
  name: limit-range-calc-resources-pod-only-limits
spec:
  containers:
  - name: nginx-web
    image: harbor.kubemsb.com/library/nginx-web:0.1
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
