apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range-pvc
spec:
  limits:
  - default:
      storage: 10Gi
    defaultRequest:
      storage: 2Gi
    max:
      storage: 20Gi
    type: PersistentVolumeClaim
