apiVersion: batch/v1
kind: Job
metadata:
  name: n-times-job
spec:
  completions: 10 # 要完成的次数
  parallelism: 1  # 每次执行的并发数量
  template:
    spec:
      containers:
      - name: busybox-job
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - echo
        - hello
      restartPolicy: Never 
